version: '3'
services:
  app:
    build:
      context: ./
      dockerfile: Dockerfile
      args:
        - WITH_XDEBUG=true
    volumes:
      - ./:/var/www/html
    environment:
      - PHP_IDE_CONFIG=serverName=project-do-good
      - XDEBUG_CONFIG=remote_host=host.docker.internal remote_port=9000
    ports:
      - 8080:80

  database:
    image: mariadb:10.5.9
    volumes:
      - doar_mariadb:/var/lib/mysql
    environment:
      - "MYSQL_DATABASE=homestead"
      - "MYSQL_USER=homestead"
      - "MYSQL_PASSWORD=secret"
      - "MYSQL_ROOT_PASSWORD=secret"
    ports:
      - "33061:3306"

volumes:
  doar_mariadb:
